import React, { useEffect, useState } from "react";
import GroupChart3 from "@/components/partials/widget/chart/group-chart-7";
import HomeBredCurbs from "./HomeBredCurbs";

import Card from "@/components/ui/Card";
import BasicArea from "../chart/appex-chart/BasicArea";

import Card2 from "@/components/ui/Card";
import EarningChart from "../../../src/components/partials/widget/chart/earning-chart1";
import SelectMonth from "@/components/partials/SelectMonth";
import HomeBredCurbs2 from "../dashboard/HomeBredCurbs";
// import GroupChart6 from "@/components/partials/widget/chart/group-chart-5";
import GroupChart6 from "../../components/partials/widget/chart/group-chart-5";
import KYC from "../components/kyc";
import Speedometer from "../../components/Speedometer2";

import { REACT_APP_BASE_URL } from "../../../index";

const _id = localStorage.getItem("_id");
const token = localStorage.getItem("token");

const Ecommerce = () => {
  const [filterMap, setFilterMap] = useState("usa");

  const [FirstDataValue, setFirstDataValue] = useState({});
  const [SecondDataValue, setSecondDataValue] = useState({});
  const [ThirdSub1DataValue, setThirdSub1DataValue] = useState({});
  const [ThirdSub2DataValue, setThirdSub2DataValue] = useState({});
  const [FourthDataValue, setFourthDataValue] = useState({});
  
  useEffect(() => {
    fetchData();
  }, []);

  const requestData = {
    period: "today",
  };

  const fetchData = () => {
    fetch(`${REACT_APP_BASE_URL}/api/restaurants/myDashboard`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify(requestData),
    })
      .then((response) => response.json())
      .then((responseData) => {
        if (responseData.code == 200) {
        
          setFirstDataValue(responseData.data.topStats);
          setSecondDataValue(responseData.data.graphData);
          setThirdSub1DataValue(responseData.data.roas);
          setThirdSub2DataValue(responseData.data.ra);
          setFourthDataValue(responseData.data.kyc);
        } else {
          console.log("API call error:", responseData.message);
        }
      })
      .catch((error) => {
        console.error("API call error:", error);
      });
  };

  const handleClick = (ParentComponentFunctionparameter) => {
    const requestData = {
      period: ParentComponentFunctionparameter,
    };
    fetch(`${REACT_APP_BASE_URL}/api/restaurants/myDashboard`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify(requestData),
    })
      .then((response) => response.json())
      .then((responseData) => {
        if (responseData.code == 200) {

          setFirstDataValue(responseData.data.topStats);
          setSecondDataValue(responseData.data.graphData);
          setThirdSub1DataValue(responseData.data.roas);
          setThirdSub2DataValue(responseData.data.ra);
          setFourthDataValue(responseData.data.kyc);
        } else {
          console.log("API call error:", responseData.message);
        }
      })
      .catch((error) => {
        console.error("API call error:", error);
      });
  };

  return (
    <>
      <div>
        <HomeBredCurbs
          title="Whatsapp Marketing"
          title2="Lorem ipsum dolor sit amet consectetur."
          handleClick={handleClick}
        />
        <div className="grid grid-cols-12 gap-5 mb-5 mt-5">
          <div className="2xl:col-span-12 lg:col-span-12 col-span-12">
            <div className="grid md:grid-cols-4 grid-cols-1 gap-4">
              <GroupChart6 FirstDataKey={FirstDataValue} />
            </div>
          </div>
        </div>
      </div>

      <div className=" space-y-5">
        <Card>
          <div class="flex flex-col md:flex-row items-center">
            <div class="md:w-1/2 md:pr-4">
              <h6 class="font-bold">Revenue Generated</h6>
              <p class="text-xs mt-1">Money generated by buyer</p>
            </div>
            <svg class="w-6 h-6 text-blue-500 dark:text-white ml-auto" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v15a1 1 0 0 0 1 1h15M8 16l2.5-5.5 3 3L17.273 7 20 9.667"/>
            </svg>
          </div>
          <BasicArea secondDataKey={SecondDataValue} />
        </Card>
      </div>

      <div className="mt-4">
        {/* <HomeBredCurbs2 title="Ecommerce" /> */}
        <div className="grid grid-cols-12 gap-5">
          <div className="col-span-12 md:col-span-6">
            {/* <Card2 title="Return On Ad Spend (ROAS)" headerslot={<SelectMonth />}> */}
            <Card2>
              <div class="flex flex-col md:flex-row items-center" >
                <div class="md:w-1/2 md:pr-4">
                  <div class="flex items-center">
                    <h6 class="font-bold text-md whitespace-nowrap">
                      Return On Ad Spend (ROAS)
                    </h6>
                  </div>
                  <div class="flex items-center mt-1">
                    <p class="text-sm">Overview of</p>
                  </div>
                </div>
                <svg class="w-5 h-5 ml-auto" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M8.9999 0.0493164L9 3.07082C5.6077 3.55606 3 6.47346 3 9.99994C3 13.8659 6.13401 16.9999 10 16.9999C11.5723 16.9999 13.0236 16.4815 14.1922 15.6063L16.3289 17.7427C14.605 19.1535 12.4014 19.9999 10 19.9999C4.47715 19.9999 0 15.5227 0 9.99994C0 4.81462 3.94662 0.551086 8.9999 0.0493164ZM19.9506 11C19.7509 13.011 18.9555 14.8467 17.7433 16.3282L15.6064 14.1921C16.2926 13.2758 16.7595 12.1858 16.9291 10.9999L19.9506 11ZM11.0011 0.0494163C15.725 0.518956 19.4815 4.27583 19.9506 8.99984L16.9291 8.99974C16.4905 5.93446 14.0661 3.50986 11.001 3.07097L11.0011 0.0494163Z" fill="#4880FF" />
                </svg>
              </div>
              <div class="flex items-center mt-4">
                <button type="button" class="flex-grow text-blue-700 hover:text-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-bold rounded-lg text-sm px-6 py-1.5 text-left inline-flex items-center border border-blue-700 mr-4" >
                  <svg width="16" height="17" viewBox="0 0 16 17" fill="none" xmlns="http://www.w3.org/2000/svg" >
                    <rect width="16" height="16" transform="translate(0 0.5)" fill="#9D3AFF"/>
                    <path d="M14 1.83325V15.1666H12.6667V9.83325H10.6667V5.16658C10.6667 3.32564 12.1591 1.83325 14 1.83325ZM6 9.76658V15.1666H4.66667V9.76658C3.14517 9.45772 2 8.11259 2 6.49992V2.49992H3.33333V7.16658H4.66667V2.49992H6V7.16658H7.33333V2.49992H8.66667V6.49992C8.6666 8.11259 7.52147 9.45772 6 9.76658Z" fill="white"/>
                  </svg>
                  &nbsp; Dine-In
                </button>
                <button type="button" disabled class="flex-grow text-blue-400 cursor-not-allowed focus:ring-4 focus:outline-none focus:ring-blue-300 font-bold rounded-lg text-sm px-6 py-1.5 text-left inline-flex items-center border border-blue-400" >
                  <svg width="21" height="20" viewBox="0 0 21 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M12.167 15V16.6667L13.8337 17.5V18.3333H7.16699L7.16398 17.503L8.83366 16.6667V15H2.99349C2.53703 15 2.16699 14.6259 2.16699 14.1604V3.33957C2.16699 2.87589 2.54642 2. 2.99349 2.5H18.0072C18.4637 2.5 18.8337 2.8741 18.8337 3.33957V14.1604C18.8337 14.6241 18.4542 1 18.0072 15H12.167ZM3.83366 11.6667V13.3333H17.167V11.6667H3.83366Z" fill="#949FAC"/>
                  </svg>
                  &nbsp; Online
                </button>
              </div>
              <div className="flex flex-col h-full">
                <div className="flex-grow">
                  <EarningChart props={ThirdSub1DataValue}/>
                </div>
              </div>
            </Card2>
          </div>
          <div className="col-span-12 md:col-span-6">
            <Card2>
              <div class="flex flex-col md:flex-row items-center">
                <div class="md:w-1/2 md:pr-4">
                  <div class="flex items-center">
                    <h6 class="font-bold text-md whitespace-nowrap">
                      Review Analysis
                    </h6>
                  </div>
                  <div class="flex items-center mt-1">
                    <p class="text-sm">Overview of</p>
                  </div>
                </div>
                <svg
                  width="20"
                  height="18"
                  viewBox="0 0 20 18"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                  class="ml-auto"
                >
                  <path
                    d="M18 10C18 12.2091 17.1046 14.2091 15.6569 15.6569L17.0711 17.0711C18.8807 15.2614 20 
            12.7614 20 10C20 4.47715 15.5228 0 10 0C4.47715 0 0 4.47715 0 10C0 12.7614 1.11929 15.2614 2.92893
            17.0711L4.34315 15.6569C2.89543 14.2091 2 12.2091 2 10C2 5.58172 5.58172 2 10 2C14.4183 2 18 
            5.58172 18 10ZM13.293 5.29297L8.5 9.5L10.5 11.5L14.7072 6.70718L13.293 5.29297Z"
                    fill="#4880FF"
                  />
                </svg>
              </div>
              <div class="flex items-center mt-3">
                <button
                  type="button"
                  class="flex-grow text-blue-700 hover:text-blue-800 focus:ring-4 
          focus:outline-none focus:ring-blue-300 font-bold rounded-lg text-sm px-6 py-1.5 text-left 
          inline-flex items-center border border-blue-700 mr-4"
                >
                  <svg
                    width="16"
                    height="17"
                    viewBox="0 0 16 17"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <rect
                      width="16"
                      height="16"
                      transform="translate(0 0.5)"
                      fill="#9D3AFF"
                    />
                    <path
                      d="M14 1.83325V15.1666H12.6667V9.83325H10.6667V5.16658C10.6667 3.32564 12.1591 1.83325 
              14 1.83325ZM6 9.76658V15.1666H4.66667V9.76658C3.14517 9.45772 2 8.11259 2 
              6.49992V2.49992H3.33333V7.16658H4.66667V2.49992H6V7.16658H7.33333V2.49992H8.66667V6.49992C8.6666
              8.11259 7.52147 9.45772 6 9.76658Z"
                      fill="white"
                    />
                  </svg>
                  &nbsp; Dine-In
                </button>
                <button
                  type="button"
                  disabled
                  class="flex-grow text-blue-400 cursor-not-allowed focus:ring-4 
          focus:outline-none focus:ring-blue-300 font-bold rounded-lg text-sm px-6 py-1.5 text-left 
          inline-flex items-center border border-blue-400"
                >
                  <svg
                    width="21"
                    height="20"
                    viewBox="0 0 21 20"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M12.167 15V16.6667L13.8337 17.5V18.3333H7.16699L7.16398 17.503L8.83366 
              16.6667V15H2.99349C2.53703 15 2.16699 14.6259 2.16699 14.1604V3.33957C2.16699 2.87589 2.54642 
              2.5 2.99349 2.5H18.0072C18.4637 2.5 18.8337 2.8741 18.8337 3.33957V14.1604C18.8337 14.6241 
              18.4542 15 18.0072 
              15H12.167ZM3.83366 11.6667V13.3333H17.167V11.6667H3.83366Z"
                      fill="#949FAC"
                    />
                  </svg>
                  &nbsp; Online
                </button>
              </div>
              <div className="flex flex-col h-full mt-4">
                <div className="flex-grow">
                  <Speedometer raDataKey={ThirdSub2DataValue}/>
                </div>
              </div>
            </Card2>
          </div>
        </div>
      </div>

      <div className="mt-3">
        <div class="px-4 sm:px-6 lg:px-8">
          <div class="py-4">
            <div class="bg-white overflow-hidden shadow-xl rounded-lg w-full p-3">
              <div class="flex flex-col md:flex-row items-center mt-2">
                <div class="md:w-1/2 md:pr-4">
                  <h6 class="font-bold">Know Your Customer</h6>
                  <p class="text-xs mt-1">Money generated by buyer</p>
                </div>
                <svg
                  width="20"
                  height="20"
                  viewBox="0 0 20 20"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                  class="ml-auto"
                >
                  <path
                    d="M10 20C4.47715 20 0 15.5228 0 10C0 4.47715 4.47715 0 10 0C15.5228 0 20 4.47715 20 10C20 
            15.5228 15.5228 20 10 20ZM10 7.5C10.8284 7.5 11.5 6.82843 11.5 6C11.5 5.17157 10.8284 4.5 10 
            4.5C9.1716 4.5 8.5 5.17157 8.5 6C8.5 6.82843 9.1716 7.5 10 7.5ZM12 
            13H11V8.5H8V10.5H9V13H8V15H12V13Z"
                    fill="#3A95FF"
                  />
                </svg>
              </div>
              <KYC FourthDataKey={FourthDataValue} />
            </div>
          </div>
        </div>
        {/* <h6 className=" font-bold p-4">Know Your Customer</h6>
      
  <KYC popularlocation={popularlocation} populardaytime={populardaytime} popularagegroup={popularagegroup} 
  popularprofession={popularprofession} /> */}
      </div>

      <div class="px-4 sm:px-6 lg:px-8">
        <div class="py-4">
          <div class=" bg-orange-100 overflow-hidden shadow-xl rounded-lg">
            <div class="px-8 py-2 sm:px-8 flex items-center">
              <svg
                width="22"
                height="22"
                viewBox="0 0 24 24"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
                class="mr-2"
              >
                <path
                  d="M7.94101 18C7.64391 16.7274 6.30412 15.6857 5.75395 14.9992C4.65645 13.6297 4 11.8915 4 10C4 
          5.58172 7.58172 2 12 2C16.4183 2 20 5.58172 20 10C20 11.8925 19.3428 13.6315 18.2443 15.0014C17.6944 
          15.687 16.3558 16.7276 16.059 18H7.94101ZM16 20V21C16 22.1046 15.1046 23 14 23H10C8.89543 23 8 
          22.1046 8 21V20H16ZM13 10.0048V6L8.5 12.0048H11V16.0048L15.5 10.0048H13Z"
                  fill="#FFB800"
                />
              </svg>
              <p class="mt-1 max-w-2xl text-xs text-gray-500 whitespace-nowrap">
                Lorem ipsum dolor sit amet consectetur. Sed quis quis tellus
                blandit integer mollis tortor. Maecenas pulvinar tincidunt leo
                ultrices
              </p>
            </div>
            <div class="border-t border-gray-200"></div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Ecommerce;
